### ISSUE TITLE
Line out?

### ISSUE THREAD

**Issue by marchingband** [CoretechR/Retro-Audio#1]
Hello, this is amazing <3
Can the headphone output function as a line level out? I know the IC you chose is a class D amplifier, so I'm wondering if you've tried connecting it to, say, the input of a home stereo. Is there a modification to the circuit design you can imagine that would easily provide line out?
thank you!

**Comment by CoretechR** [comment]
Hi, the output on the pcb is basically the same as on a smartphone. As far as I know the difference between a headphone output and a line out is the amplifier. If you set the headphone out to a fixed volume this should work with a home stereo. The main reason for a line out is that you don't need an internal amplifier and have better sound quality.
But I am far from an expert on audio and have not tried the output with anything but headphones. Maybe you can test if your stereo works with a phone, then the Retro Audio should work as well.

**Comment by marchingband** [comment]
Thanks for the response. My iPhone works well enough with my stereo, I'll do some tests with that IC and post again after :)
