### ISSUE TITLE
What is C1, R12, R15, R27?

### ISSUE THREAD

**Issue by krokodil66** [CoretechR/Retro-Audio#3]
Very cool project ;-)).

Could not find part "C1" in the BOM. It seems part of the Audio Output Stage. Is it a normal 0.1uF SMD capacitor? on Aisler.net is "\!0.01uF" shown in the part list.
Would be the following OK?:
Vishay | K103K10X7RF5UL2 | Multilayer Ceramic Capacitors MLCC - Leaded K 50V 10NF +/-10% X7R AMMO E3

R12, R15 is also missing on BOM. Is R27 976k or 10k?

**Comment by CoretechR** [comment]
The parts marked with a "!" are not populated. I forgot to mention that in the documentation. I'm definitely going to update the files to add this, thanks!
Any yes, the values you found in the schematic are correct. The resistors are for configuring the output gain. The capacitor is not really necessary, I just left that in if the audio needs filtering.
