### ISSUE TITLE
Question gain

### ISSUE THREAD

**Issue by olup** [CoretechR/Retro-Audio#6]
Hi, I am using your schematics as an inspiration to design an audio product, and I am wondering where is the GAIN management (and SD_MODE). The label in the sheet goes nowhere:
<img width="573" alt="image" src="https://github.com/CoretechR/Retro-Audio/assets/13785588/eefabfcf-0d3c-4817-a74e-e4b96a41090e">
Could you give some detail about it ?

Many thanks !

**Comment by CoretechR** [comment]
Hi the gain is fixed to around 8dB by leaving the pin floating.
<img width="1182" alt="image" src="https://github.com/CoretechR/Retro-Audio/assets/13223470/a3486cdb-9429-4cc6-8a18-9375004515e3">
The audio volume is set via the i2s data. That's handled by the i2s library.

**Comment by olup** [comment]
Many thanks. Same for the SD MODE ? You leave it floating for channel mixing ?

May I ask what is your experience with the max98357a with the headphones ? Is that good enough ?

Finally, I was meant to ask - what is the speaker you used in your project ? Are you happy with it ?

**Comment by CoretechR** [comment]
Yes, the SD mode is set to mono audio, because there is only one audio driver. I built this mainly for listening to audiobooks and that works very well even with the internal speaker. But the audio quality is not so great. As there are only 21 volume levels, you really only have 5 or so levels for headphones because they are louder. It really depends on what you want to make.

**Comment by olup** [comment]
Indeed - I am making a story/podcast player. I guess this does the trick nicely then. Any Intel on the speaker part you used ? I am considering the options. 

Thanks a lot anyway

**Comment by CoretechR** [comment]
No problem, this is the speaker I used: https://www.mouser.de/ProductDetail/490-CDS-40304-L100

**Comment by olup** [comment]
Thanks again. Is that fine if I use this channel for a few more questiosn ?

For instance, to keep a wide array of gain in the headphone mode, could I plug the GAIN pin of the max on a esp32 gpio to programmatically change the gain multiplier (GPIO low acting as GND connexion - high as VCC) ?

Another one - you seemed to have use SPI interface for the SD over sdmmc - is that fast enough in your experience ?

Thanks again
